=== mvDanilov/XmlTack_3/src/main/java/entity/Abonent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.example.com/abonent" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ab.abonent" type="abon:ab.abonentType" xmlns:abon="http://www.example.com/abonent"/>
    <xs:complexType name="employeesType">
        <xs:sequence>
            <xs:element type="abon:employeeType" name="employee" xmlns:abon="http://www.example.com/abonent"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element type="xs:string" name="city"/>
            <xs:element name="street">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Bulvar-Mira"/>
                        <xs:enumeration value="Stepnoy-3"/>
                        <xs:enumeration value="Stepnoy-1"/>
                        <xs:enumeration value="Stepnoy-2"/>
                        <xs:enumeration value="Orbita"/>
                        <xs:enumeration value="Orbita-2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="build">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="28"/>
                        <xs:enumeration value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="apartment">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="28"/>
                        <xs:enumeration value="33"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientsType">
        <xs:sequence>
            <xs:element type="abon:clientType" name="client" maxOccurs="unbounded" minOccurs="0" xmlns:abon="http://www.example.com/abonent"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element type="abon:fullNameType" name="fullName" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element type="abon:addressType" name="address" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element type="abon:orderType" name="order" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element name="telephone">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="33-33-33"/>
                        <xs:enumeration value="44-44-44"/>
                        <xs:enumeration value="11-11-11"/>
                        <xs:enumeration value="55-55-55"/>
                        <xs:enumeration value="66-66-66"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="mobilePhone" minOccurs="0"/>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Ivan@mail.ru"/>
                        <xs:enumeration value="Petr@mail.ru"/>
                        <xs:enumeration value="Fedr@mail.ru"/>
                        <xs:enumeration value="Vlad@mail.ru"/>
                        <xs:enumeration value="Zhid@mail.ru"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id" use="optional"/>
    </xs:complexType>
    <xs:complexType name="fullNameType">
        <xs:sequence>
            <xs:element name="surname">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Kanatov"/>
                        <xs:enumeration value="Ivanov"/>
                        <xs:enumeration value="Petrov"/>
                        <xs:enumeration value="Sidorov"/>
                        <xs:enumeration value="Sholohov"/>
                        <xs:enumeration value="Zhidov"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="firstname">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Talgat"/>
                        <xs:enumeration value="Ivan"/>
                        <xs:enumeration value="Petr"/>
                        <xs:enumeration value="Fedor"/>
                        <xs:enumeration value="Vladimir"/>
                        <xs:enumeration value="Artur"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="middlename">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Zhaksiadamov"/>
                        <xs:enumeration value="Ivanovich"/>
                        <xs:enumeration value="Petrovich"/>
                        <xs:enumeration value="Vladimirovich"/>
                        <xs:enumeration value="Abramovich"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ab.abonentType">
        <xs:sequence>
            <xs:element type="abon:employeesType" name="employees" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element type="abon:clientsType" name="clients" xmlns:abon="http://www.example.com/abonent"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element type="abon:fullNameType" name="fullName" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element type="abon:addressType" name="address" xmlns:abon="http://www.example.com/abonent"/>
            <xs:element type="xs:string" name="telephone"/>
            <xs:element type="xs:string" name="mobilePhone"/>
            <xs:element type="xs:string" name="identityCard"/>
            <xs:element type="xs:string" name="function"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id"/>
    </xs:complexType>
    <xs:complexType name="orderType">
        <xs:sequence>
            <xs:element type="xs:string" name="count"/>
            <xs:element type="xs:string" name="period"/>
            <xs:element type="xs:string" name="price"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mvDanilov/XmlTack_3/src/main/resources/Abonent.xml
<?xml version="1.0"?>
<ab.abonent xmlns="http://www.example.com/abonent"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.com/corporation Abonent.xsd">
    <employees>
        <employee id="011">
            <fullName>
                <surname>Kanatov</surname>
                <firstname>Talgat</firstname>
                <middlename>Zhaksiadamov</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Bulvar-Mira</street>
                <build>28</build>
                <apartment>28</apartment>
            </address>
            <telephone>555-66-11</telephone>
            <mobilePhone>8-777-555-66-11</mobilePhone>
            <identityCard>12345678</identityCard>
            <function>Director</function>
        </employee>
    </employees>

    <clients>
        <client id="001">
            <fullName>
                <surname>Ivanov</surname>
                <firstname>Ivan</firstname>
                <middlename>Ivanovich</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Stepnoy-3</street>
                <build>3</build>
                <apartment>33</apartment>
            </address>
            <order>
                <count>2</count>
                <period>till 2:00</period>
                <price>500</price>
            </order>
            <telephone>33-33-33</telephone>
            <mobilePhone>33-33-33</mobilePhone>
            <email>Ivan@mail.ru</email>
        </client>

        <client id="002">
            <fullName>
                <surname>Petrov</surname>
                <firstname>Petr</firstname>
                <middlename>Petrovich</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Stepnoy-1</street>
                <build>3</build>
                <apartment>33</apartment>
            </address>
            <order>
                <count>2</count>
                <period>till 2:00</period>
                <price>500</price>
            </order>
            <telephone>44-44-44</telephone>
            <email>Petr@mail.ru</email>
        </client>

        <client id="003">
            <fullName>
                <surname>Sidorov</surname>
                <firstname>Fedor</firstname>
                <middlename>Ivanovich</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Stepnoy-2</street>
                <build>3</build>
                <apartment>33</apartment>
            </address>
            <order>
                <count>2</count>
                <period>till 2:00</period>
                <price>500</price>
            </order>
            <telephone>11-11-11</telephone>
            <email>Fedr@mail.ru</email>
        </client>

        <client id="004">
            <fullName>
                <surname>Sholohov</surname>
                <firstname>Vladimir</firstname>
                <middlename>Vladimirovich</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Orbita</street>
                <build>3</build>
                <apartment>33</apartment>
            </address>
            <order>
                <count>2</count>
                <period>till 2:00</period>
                <price>500</price>
            </order>
            <telephone>55-55-55</telephone>
            <email>Vlad@mail.ru</email>
        </client>

        <client id="005">
            <fullName>
                <surname>Zhidov</surname>
                <firstname>Artur</firstname>
                <middlename>Abramovich</middlename>
            </fullName>
            <address>
                <city>Karaganda</city>
                <street>Orbita-2</street>
                <build>3</build>
                <apartment>33</apartment>
            </address>
            <order>
                <count>2</count>
                <period>till 2:00</period>
                <price>500</price>
            </order>
            <telephone>66-66-66</telephone>
            <email>Zhid@mail.ru</email>
        </client>
    </clients>

</ab.abonent>
